name: Lint Go Code

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.26.0
          args: --timeout=5m
