name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    ## Checkout project source code
    - uses: actions/checkout@v4
    
    ## Build Docker image with commit SHA tag
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nitink1919/go-api:${{ github.sha }}

    ## Publish image to Docker Hub
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: nitink1919/go-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"
