on:
  push:
    branches:
      - main

name: Test Across Matrix

jobs:
  test:
    # Define a strategy for the job with multiple test combinations
    strategy:
      # Define the matrix of Go versions and platforms to test against
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x, 1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    # Defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    
    steps:
      # Checkout code to work with local files
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup Go environment based on matrix version
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # Run Go tests
      - name: Test
        run: go test ./...
